# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: News
    url: '/post/'
    weight: 20
  - name: Research
    url: '/research/'
    weight: 30
  - name: Spectroscopy of Liquid Jets
    url: '/research/liquid_jets/'
    parent: Research
    weight: 31
  - name: Laser Ablation Synthesis
    url: '/research/lasis/'
    parent: Research
    weight: 32
  - name: High Resolution Spectroscopy
    url: '/research/high_res/'
    parent: Research
    weight: 33
  - name: Cluster Chemistry in Space
    url: '/research/metal_clusters/'
    parent: Research
    weight: 34
  - name: Publications
    url: '/publication/'
    weight: 40
  - name: Team
    url: '/team/'
    weight: 50
  - name: People
    url: '/team/people/'
    parent: Team
    weight: 51
  - name: Values
    url: '/team/values/'
    parent: Team
    weight: 52
  - name: Vacancies
    url: '/team/vacancies/'
    parent: Team
    weight: 53
  - name: Contact
    url: '/contact/'
    weight: 70

#  - name: Tour
#    url: /tour
#    weight: 10

#  - name: Events
#    url: /event
#    weight: 50

