# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: /tour
    weight: 10
  - name: News
    url: /post
    weight: 20
  - name: People
    url: /people
    weight: 30
  - name: Research
    url: /research
    identifier: research
    weight: 40
  - name: Spectroscopy of Liquid Jets
    url: /research/liquid_jets
    parent: research
    weight: 41
  - name: High Resolution Spectroscopy
    url: /research/high_res
    parent: research
    weight: 42
  - name: Cluster Chemistry in Space
    url: /research/metal_clusters
    parent: research
    weight: 43
  - name: Events
    url: /event
    weight: 50
  - name: Publications
    url: /publication
    weight: 60
  - name: Contact
    url: /contact
    weight: 70
